
import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raja C
 */
public class products extends javax.swing.JFrame {

    /**
     * Creates new form products
     */
    public products() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox<>();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jComboBox7 = new javax.swing.JComboBox<>();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jComboBox8 = new javax.swing.JComboBox<>();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jComboBox9 = new javax.swing.JComboBox<>();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jComboBox10 = new javax.swing.JComboBox<>();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("    Products");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Quantity");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Price");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lux", "Lifeboy", "Dettol", "Dove", "Cinthol", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fair & lovely", "Fair& handsome", "Ponds", "Garnier", "Himalaya" }));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "head & shoulder", "Clinic Plus", "Dove", "Meera", "Sunsilk" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lays", "Bingo", "Kurkure", "Uncle chips", "Noodles babblu" }));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sprite", "7 up", "Thumbs up", "Coco cola", "Pepsi" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("BUY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Beverages");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Soap");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Shampoo");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Chips");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Face Cream");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, 120, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextField3)
                    .addComponent(jTextField4))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addComponent(jTextField9)))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("    Products");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Quantity");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Price");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lux", "Lifeboy", "Dettol", "Dove", "Cinthol", " " }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jTextField12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fairandlovely", "Fairandhandsome", "Ponds", "Garnier", "Himalaya" }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "headandshoulder", "ClinicPlus", "Dove", "Meera", "Sunsilk" }));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });

        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lays", "Bingo", "Kurkure", "Unclechips", "Noodlesbabblu" }));
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });

        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });

        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sprite", "Sevenup", "Thumbsup", "Cococola", "Pepsi" }));
        jComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });

        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });

        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Beverages");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Soap");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Shampoo");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Chips");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Face Cream");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(50, 50, 50)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox9, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox8, javax.swing.GroupLayout.Alignment.LEADING, 0, 101, Short.MAX_VALUE)
                            .addComponent(jComboBox7, 0, 101, Short.MAX_VALUE)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(jTextField19, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField13, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField12)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextField13)
                    .addComponent(jTextField14))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addComponent(jTextField18, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField20, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addComponent(jTextField19)))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        jComboBox1.addItem("lux");

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed

        //jComboBox1.addItem("lux");
        if(jComboBox6.getSelectedItem().equals("Lux")){
            jTextField14.setText("10");}
        if(jComboBox6.getSelectedItem().equals("Lifeboy")){
            jTextField14.setText("15");}
        if(jComboBox6.getSelectedItem().equals("Dettol")){
            jTextField14.setText("20");}
        if(jComboBox6.getSelectedItem().equals("Dove")){
            jTextField14.setText("40");}
        if(jComboBox6.getSelectedItem().equals("Cinthol")){
            jTextField14.setText("30");}
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
       if(jComboBox8.getSelectedItem().equals("headandshoulder")){
            jTextField16.setText("5");}
       if(jComboBox8.getSelectedItem().equals("ClinicPlus")){
            jTextField16.setText("3");}
       if(jComboBox8.getSelectedItem().equals("Dove")){
            jTextField16.setText("5");}
       if(jComboBox8.getSelectedItem().equals("Meera")){
            jTextField16.setText("10");}
       if(jComboBox8.getSelectedItem().equals("Sunsilk")){
            jTextField16.setText("2");}
       
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
if(jComboBox10.getSelectedItem().equals("Sprite"))
        { jTextField12.setText("50");
        }       
        if(jComboBox10.getSelectedItem().equals("Sevenup"))
        {
            jTextField12.setText("25");
        }
        if(jComboBox10.getSelectedItem().equals("Thumbsup"))
        {
            jTextField12.setText("20");
        }
         if(jComboBox10.getSelectedItem().equals("Cococola"))
        {
            jTextField12.setText("25");
        }
          if(jComboBox10.getSelectedItem().equals("Pepsi"))
        {
            jTextField12.setText("15");
        } 
        
        
              
    }//GEN-LAST:event_jComboBox10ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   if(jComboBox10.getSelectedItem().equals("Sprite"))
        {
            Object Sprite=jComboBox10.getSelectedItem();
            String qty=jTextField11.getText();
            String price="50";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0 ; 
               a=a+Amt;
       
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Sprite+"' , '"+qty+"' , '"+price+"', '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query);  
            
            String query1="INSERT INTO admin VALUES('"+Sprite+"' , '"+qty+"' , '"+price+"', '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query1);  
            
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
        
           if(jComboBox10.getSelectedItem().equals("Sevenup"))
        {
            Object Sevenup=jComboBox10.getSelectedItem();
            String qty=jTextField11.getText();
            String price="25";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con1 = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con1.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Sevenup+"' , '"+qty+"' , '"+price+"' ,  '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query);  
            
            String query1="INSERT INTO admin VALUES('"+Sevenup+"' , '"+qty+"' , '"+price+"', '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query1);  
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        
        }
   if(jComboBox10.getSelectedItem().equals("Thumbsup"))
        {
            Object Thumbsup=jComboBox10.getSelectedItem();
            String qty=jTextField11.getText();
            String price="20";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Thumbsup+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query); 
            
            String query1="INSERT INTO admin VALUES('"+Thumbsup+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query1); 
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
    if(jComboBox10.getSelectedItem().equals("Cococola"))
        {
            Object Cococola=jComboBox10.getSelectedItem();
            String qty=jTextField11.getText();
            String price="25";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Cococola+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query); 
            
            String query1="INSERT INTO admin VALUES('"+Cococola+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query1); 
            }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
    if(jComboBox10.getSelectedItem().equals("Pepsi"))
        {
            Object Pepsi=jComboBox10.getSelectedItem();
            String qty=jTextField11.getText();
            String price="15";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Pepsi+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query);
            
            String query1="INSERT INTO admin VALUES('"+Pepsi+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query1);
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
    if(jComboBox6.getSelectedItem().equals("Lux"))
        {
            Object Lux=jComboBox6.getSelectedItem();
            String qty=jTextField13.getText();
            String price="10";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Lux+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query);
            
            String query1="INSERT INTO admin VALUES('"+Lux+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query1);
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
    if(jComboBox6.getSelectedItem().equals("Lifeboy"))
        {
            Object Lifeboy=jComboBox6.getSelectedItem();
            String qty=jTextField13.getText();
            String price="20";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Lifeboy+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query);
            
            String query1="INSERT INTO admin VALUES('"+Lifeboy+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query1);
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
     if(jComboBox6.getSelectedItem().equals("Dettol"))
        {
            Object Dettol=jComboBox6.getSelectedItem();
            String qty=jTextField13.getText();
            String price="20";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Dettol+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query);
            
            String query1="INSERT INTO admin VALUES('"+Dettol+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query1);
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
     if(jComboBox6.getSelectedItem().equals("Dove"))
        {
            Object Dove=jComboBox6.getSelectedItem();
            String qty=jTextField13.getText();
            String price="40";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Dove+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query);
            
            String query1="INSERT INTO admin VALUES('"+Dove+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query1);
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
     if(jComboBox6.getSelectedItem().equals("Cinthol"))
        {
            Object Cinthol=jComboBox6.getSelectedItem();
            String qty=jTextField13.getText();
            String price="15";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Cinthol+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query); 
            
            String query1="INSERT INTO admin VALUES('"+Cinthol+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query1); 
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
    if(jComboBox8.getSelectedItem().equals("headandshoulder"))
        {
            Object headandshoulder=jComboBox8.getSelectedItem();
            String qty=jTextField15.getText();
            String price="5";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+headandshoulder+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query);
            
            String query1="INSERT INTO admin VALUES('"+headandshoulder+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query1);
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
    if(jComboBox8.getSelectedItem().equals("ClinicPlus"))
        {
            Object ClinicPlus=jComboBox8.getSelectedItem();
            String qty=jTextField15.getText();
            String price="3";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+ClinicPlus+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query);
            
            String query1="INSERT INTO admin VALUES('"+ClinicPlus+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query1);
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
    if(jComboBox8.getSelectedItem().equals("Dove"))
        {
            Object Dove=jComboBox8.getSelectedItem();
            String qty=jTextField15.getText();
            String price="5";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Dove+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query); 
            
            String query1="INSERT INTO admin VALUES('"+Dove+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query1); 
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
    if(jComboBox8.getSelectedItem().equals("Meera"))
        {
            Object Meera=jComboBox8.getSelectedItem();
            String qty=jTextField15.getText();
            String price="10";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Meera+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query);
            
            String query1="INSERT INTO admin VALUES('"+Meera+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query1);
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
    if(jComboBox8.getSelectedItem().equals("Sunsilk"))
        {
            Object Sunsilk=jComboBox8.getSelectedItem();
            String qty=jTextField15.getText();
            String price="2";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Sunsilk+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query);
            
            String query1="INSERT INTO admin VALUES('"+Sunsilk+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query1);
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
    if(jComboBox9.getSelectedItem().equals("Lays"))
        {
            Object Lays=jComboBox9.getSelectedItem();
            String qty=jTextField17.getText();
            String price="10";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Lays+"' , '"+qty+"' , '"+price+"', '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query); 
            
            String query1="INSERT INTO admin VALUES('"+Lays+"' , '"+qty+"' , '"+price+"', '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query1); 
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
    if(jComboBox9.getSelectedItem().equals("Bingo"))
        {
            Object Bingo=jComboBox9.getSelectedItem();
            String qty=jTextField17.getText();
            String price="10";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Bingo+"' , '"+qty+"' , '"+price+"', '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query);  
            
            String query1="INSERT INTO admin VALUES('"+Bingo+"' , '"+qty+"' , '"+price+"', '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query1);  
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
    
    if(jComboBox9.getSelectedItem().equals("Kurkure"))
        {
            Object Kurkure=jComboBox9.getSelectedItem();
            String qty=jTextField17.getText();
            String price="15";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Kurkure+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+qu+"' );";
            stmt.executeUpdate(query); 
            
            String query1="INSERT INTO admin VALUES('"+Kurkure+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+qu+"' );";
            stmt.executeUpdate(query1); 
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
    if(jComboBox9.getSelectedItem().equals("Unclechips"))
        {
            Object Unclechips=jComboBox9.getSelectedItem();
            String qty=jTextField17.getText();
            String price="3";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Unclechips+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+qu+"' );";
            stmt.executeUpdate(query);
            
            String query1="INSERT INTO admin VALUES('"+Unclechips+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+qu+"' );";
            stmt.executeUpdate(query1);
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
     if(jComboBox9.getSelectedItem().equals("Noodlesbabblu"))
        {
            Object Noodlesbabblu=jComboBox9.getSelectedItem();
            String qty=jTextField17.getText();
            String price="2";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Noodlesbabblu+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query);
            
            String query1="INSERT INTO admin VALUES('"+Noodlesbabblu+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query1);
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
    if(jComboBox7.getSelectedItem().equals("Fairandlovely"))
        {
            Object Fairandlovely=jComboBox7.getSelectedItem();
            String qty=jTextField19.getText();
            String price="5";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Fairandlovely+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query); 
            
            String query1="INSERT INTO admin VALUES('"+Fairandlovely+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query1); 
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
    if(jComboBox7.getSelectedItem().equals("Fairandhandsome"))
        {
            Object Fairandhandsome=jComboBox7.getSelectedItem();
            String qty=jTextField19.getText();
            String price="10";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Fairandhandsome+"' , '"+qty+"' , '"+price+"' , '"+qu+"' );";
            stmt.executeUpdate(query); 
            
            String query1="INSERT INTO admin VALUES('"+Fairandhandsome+"' , '"+qty+"' , '"+price+"' , '"+qu+"' );";
            stmt.executeUpdate(query1); 
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
     if(jComboBox7.getSelectedItem().equals("Ponds"))
        {
            Object Ponds=jComboBox7.getSelectedItem();
            String qty=jTextField19.getText();
            String price="5";
             int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
             int qu=(Amt * u);
             int a=0;
             a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Ponds+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query);  
            
            String query1="INSERT INTO admin VALUES('"+Ponds+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query1);  
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
    if(jComboBox7.getSelectedItem().equals("Garnier"))
        {
            Object Garnier=jComboBox7.getSelectedItem();
            String qty=jTextField19.getText();
            String price="30";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Garnier+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query);
            
            String query1="INSERT INTO admin VALUES('"+Garnier+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query1);
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
    if(jComboBox7.getSelectedItem().equals("Himalaya"))
        {
            Object Himalaya=jComboBox7.getSelectedItem();
            String qty=jTextField19.getText();
            String price="20";
            int Amt;
       Amt = Integer.parseInt(price);
       int u=Integer.parseInt(qty);
       int qu=(Amt * u);
       int a=0;
       a=a+Amt;
            try
        {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection)
                    DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
            Statement stmt = (Statement) con.createStatement();
           
            String query="INSERT INTO purchased VALUES('"+Himalaya+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query);
            
            String query1="INSERT INTO admin VALUES('"+Himalaya+"' , '"+qty+"' , '"+price+"' , '"+qu+"' , '"+a+"' );";
            stmt.executeUpdate(query1);
            
                    
           //JOptionPane.showMessageDialog (null, "Singup Sucessful.", "Success", JOptionPane.INFORMATION_MESSAGE);
          }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this , e.getMessage());
        }
        }
    
    
        BILL b=new BILL();
        b.setVisible(true);
    
        /*try
        {   
                Class.forName("com.mysql.jdbc.Driver");
    Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/rms" , "root" , "gounder");
    PreparedStatement pstmt = conn.prepareStatement("select bevprice from beverages ");
                
    ResultSet rs = pstmt.executeQuery();
                while(rs.next())
                {
                    jTextField12.setText(rs.getString("bevprice"));
                    jTextField14.setText(rs.getString("bevprice"));
                    jTextField16.setText(rs.getString("bevprice"));
                    jTextField18.setText(rs.getString("bevprice"));
                    jTextField20.setText(rs.getString("bevprice"));
                }
            }
        catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null , e);
        }
            finally{
                try{
                    conn.close();
                    pstmt.close();
                    rs.close();
                }
                catch(Exception e){
                    
                }
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
//uguy        // TODO add your handling code here:
        }*/
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        if(jComboBox9.getSelectedItem().equals("Lays")){
            jTextField18.setText("10");}
        if(jComboBox9.getSelectedItem().equals("Bingo")){
            jTextField18.setText("5");}
        if(jComboBox9.getSelectedItem().equals("Kurkure")){
            jTextField18.setText("15");}
        if(jComboBox9.getSelectedItem().equals("Unclechips")){
            jTextField18.setText("3");}
        if(jComboBox9.getSelectedItem().equals("Noodlesbabblu")){
            jTextField18.setText("2");}
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
       if(jComboBox7.getSelectedItem().equals("Fairandlovely")){
            jTextField20.setText("5");}
       if(jComboBox7.getSelectedItem().equals("Fairandhandsome")){
            jTextField20.setText("10");}
       if(jComboBox7.getSelectedItem().equals("Ponds")){
            jTextField20.setText("5");}
       if(jComboBox7.getSelectedItem().equals("Garnier")){
            jTextField20.setText("20");}
       if(jComboBox7.getSelectedItem().equals("Himalaya")){
            jTextField20.setText("30");}
    }//GEN-LAST:event_jComboBox7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new products().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    private static class pstmt {

        private static void close() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public pstmt() {
        }
    }

    private static class rs {

        private static void close() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public rs() {
        }
    }
}
